src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('storage/', include('storage.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

src/users/urls.py
from django.urls import path, include
from django.contrib.auth import views

from users.views import (
    WorkerSignupView, 
    WorkerLoginView, 
    WorkerProfile,
    WorkerProfileEdit, 
    EmployerProfile, 
    EmployerSignupView,
    EmployerProfileEdit,
    )


app_name = 'users'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('signup/', WorkerSignupView.as_view(), name='work_signup'),
    path('login/', WorkerLoginView.as_view(), name='work_login'),
    path('profile', WorkerProfile.as_view(), name='work_profile'),
    path('profile/edit', WorkerProfileEdit.as_view(), name='work_editprofile'),

    path('signup/emp/', EmployerSignupView.as_view(), name='emp_signup'),
    path('profile/emp/', EmployerProfile.as_view(), name='emp_profile'),
    path('profile/emp/edit', EmployerProfileEdit.as_view(), name='emp_editprofile'),
]

src/vacancies/urls.py
from django.urls import path

from vacancies.views import VacanciesPageView, VacancyDetailView

app_name = 'vacancies'

urlpatterns = [
    path('', VacanciesPageView.as_view(), name='vacancies'),
    path('<int:vacancy_id>', VacancyDetailView.as_view(), name='vacancies_detail'),
]

src/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <title>Document</title>
</head>
<body>
    <nav class="border-b border-gray-300">
        <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
            <div class="menu-left flex items-center space-x-6">
                <a href="{% url 'frontpage' %}" class="py-4 text-lg text-black-800 font-semibold">
                    <img src="https://sun9-23.userapi.com/impg/bu9ZEvAwaOLby453104YFHCVfAL0Ra3Xq8tQXA/DGIeqUuCzw0.jpg?size=645x85&quality=96&sign=2b5aa9eb1c73647adda3894e1b5e91a3&type=album" width="175" height="85" alt="NIKA">
                </a>
                <ul class="flex items-center space-x-4">
                    <li><a href="#"class="font-mono text-black hover:text-gray-600">Доступные задания</a></li>
                    <li><a href="#"class="font-mono text-black hover:text-gray-600">Рейтинг</a></li>
                    {% if request.user.type == "WORKER" %}
                    <li><a href="{% url 'vacancies:vacancies' %}"class="font-mono text-black hover:text-gray-600">Вакансии</a></li>
                    {% else %}  
                    <li><a href="#"class="font-mono text-black hover:text-gray-600">Отклики</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="menu-right flex items-center space-x-4">
                {% if request.user.is_authenticated %}
                <h1 class="text-black hover:text-gray-600">{{ user.get_username }}</h1>
                {% if request.user.type == "WORKER" %}
                <a href="{% url 'users:work_profile' %}" class="text-black hover:text-gray-600">
                    <button class="user font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                        </svg>                     
                    </a>
                </a>
                {% else %}
                <a href="{% url 'users:emp_profile' %}" class="text-black hover:text-gray-600">
                    <button class="user font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                        </svg>                     
                    </a>
                </a>
                {% endif %}
                {% if request.user.type == "WORKER" %}
                <a href="{% url 'storage:savedvacancies.html' %}" class="text-black hover:text-gray-600">
                    <button class="savedvacancies font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 14.15v4.25c0 1.094-.787 2.036-1.872 2.18-2.087.277-4.216.42-6.378.42s-4.291-.143-6.378-.42c-1.085-.144-1.872-1.086-1.872-2.18v-4.25m16.5 0a2.18 2.18 0 00.75-1.661V8.706c0-1.081-.768-2.015-1.837-2.175a48.114 48.114 0 00-3.413-.387m4.5 8.006c-.194.165-.42.295-.673.38A23.978 23.978 0 0112 15.75c-2.648 0-5.195-.429-7.577-1.22a2.016 2.016 0 01-.673-.38m0 0A2.18 2.18 0 013 12.489V8.706c0-1.081.768-2.015 1.837-2.175a48.111 48.111 0 013.413-.387m7.5 0V5.25A2.25 2.25 0 0013.5 3h-3a2.25 2.25 0 00-2.25 2.25v.894m7.5 0a48.667 48.667 0 00-7.5 0M12 12.75h.008v.008H12v-.008z" />
                        </svg>                          
                    </a>
                </a>
                {% endif %}
                <form method="POST" action="{% url 'account_logout' %}" class="text-black hover:text-gray-600">
                    {% csrf_token %}
                    <button class="font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">Выход</a>
                </form>
                {% else %}
                <a href="{% url 'users:emp_signup' %}" class="text-black hover:text-gray-600">
                    <button class="font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">Для компаний</a>
                </a>
                <a href="{% url 'users:work_signup' %}" class="text-black hover:text-gray-600">
                    <button class="font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">Для работников</a>
                </a>
                <a href="{% url 'account_login' %}" class="text-black hover:text-gray-600">
                    <button class="font-mono px-3 py-3 rounded-xl text-black bg-teal-200 hover:bg-teal-500">Войти</a>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}

        {% block scripts %}
        {% endblock %}
    </main>
</body>
</html>