src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('storage/', include('storage.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

src/users/urls.py
from django.urls import path, include
from django.contrib.auth import views

from users.views import (
    WorkerSignupView, 
    WorkerLoginView, 
    WorkerProfile,
    WorkerProfileEdit, 
    EmployerProfile, 
    EmployerSignupView,
    EmployerProfileEdit,
    )


app_name = 'users'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('signup/', WorkerSignupView.as_view(), name='work_signup'),
    path('login/', WorkerLoginView.as_view(), name='work_login'),
    path('profile', WorkerProfile.as_view(), name='work_profile'),
    path('profile/edit', WorkerProfileEdit.as_view(), name='work_editprofile'),

    path('signup/emp/', EmployerSignupView.as_view(), name='emp_signup'),
    path('profile/emp/', EmployerProfile.as_view(), name='emp_profile'),
    path('profile/emp/edit', EmployerProfileEdit.as_view(), name='emp_editprofile'),
]

src/users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


class CustomUser(AbstractUser):
    class Types(models.TextChoices):
        EMPLOYER = "EMPLOYER", "Employer"
        WORKER = "WORKER", "Worker"

    base_type = Types.WORKER
    type = models.CharField(max_length=50, choices=Types.choices, default=base_type)
    avatar = models.ImageField(upload_to='profile_images', blank=True)

    def get_absolute_url(self):
        return reverse("users_detail", kwargs={"username": self.username})
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.type = self.base_type
        return super().save(*args, **kwargs)
      
class EmployerManager(models.Manager):
    def normalize_email(self, email):
        return BaseUserManager.normalize_email(email)
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=CustomUser.Types.EMPLOYER)

class Employer(CustomUser):
    base_type = CustomUser.Types.EMPLOYER
    objects = EmployerManager()

    @property
    def more(self):
        return self.employermore
    
    class Meta:
        proxy = True

class EmployerMore(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    social = models.CharField(max_length=150, blank=True)
    areas_of_activity = models.CharField(max_length=150, blank=True)
    about = models.CharField(max_length=1024, blank=True)
    rate = models.FloatField([MinValueValidator(0.0), MaxValueValidator(10.0)], default=0)

    def __str__(self):
        return self.user.username

class WorkerManager(models.Manager):
    def normalize_email(self, email):
        return BaseUserManager.normalize_email(email)
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=CustomUser.Types.WORKER)

class Worker(CustomUser):
    base_type = CustomUser.Types.WORKER
    objects = WorkerManager()

    @property
    def more(self):
        return self.workermore
    
    class Meta:
        proxy = True

class WorkerMore(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    city = models.CharField(max_length=150, blank=True)
    ready_to_relocate = models.BooleanField(default=True, blank=True)
    position = models.CharField(max_length=150, blank=True)
    bio = models.CharField(max_length=512, blank=True)

    github_username = models.CharField(max_length=256, blank=True, db_index=True, default="")
    telegram_username = models.CharField(max_length=256, blank=True, db_index=True, default="")

    def __str__(self):
        return self.user.username

src/users/forms.py
from django.utils.translation import gettext_lazy as _
from allauth.account.forms import SignupForm
from django import forms

from .models import (
    CustomUser, 
    WorkerMore, 
    EmployerMore
    )


class EmployerSignupForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def custom_signup(self, request, user):
        user.type = CustomUser.Types.EMPLOYER
        user.save()

class WorkerSignupForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def custom_signup(self, request, user):
        user.type = CustomUser.Types.WORKER
        user.save()


class UpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=50, required=False)
    email = forms.EmailField(required=False)
    first_name = forms.CharField(max_length=50, required=False)
    last_name = forms.CharField(max_length=50, required=False)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name']

class WorkerUpdateFormMore(forms.ModelForm):
    city = forms.CharField(max_length=150, required=False)
    ready_to_relocate = forms.BooleanField(required=False)
    position = forms.CharField(max_length=150, required=False)
    bio = forms.CharField(max_length=512, required=False)
    telegram_username = forms.CharField(max_length=256, required=False)
    github_username = forms.CharField(max_length=256, required=False)
    
    class Meta:
        model = WorkerMore
        fields = ['city', 'ready_to_relocate', 'position', 'bio', 'github_username', 'telegram_username',]

class EmployerUpdateFormMore(forms.ModelForm):
    city = forms.CharField(max_length=150, required=False)
    ready_to_relocate = forms.BooleanField(required=False)
    position = forms.CharField(max_length=150, required=False)
    bio = forms.CharField(max_length=512, required=False)
    telegram_username = forms.CharField(max_length=256, required=False)
    github_username = forms.CharField(max_length=256, required=False)
    
    class Meta:
        model = EmployerMore
        fields = ['city', 'ready_to_relocate', 'position', 'bio', 'github_username', 'telegram_username',]
    

src/users/views.py
from allauth.account.views import LoginView, SignupView
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

from .mixins import EmployerRequiredMixin, WorkerRequiredMixin
from users.forms import (
    EmployerSignupForm, 
    WorkerSignupForm, 
    UpdateForm, 
    WorkerUpdateFormMore, 
    EmployerUpdateFormMore
    )


class EmployerSignupView(SignupView, TemplateView):
    template_name = 'users/employer/emp_signup.html'
    form_class = EmployerSignupForm

    def get_context_data(self, **kwargs):
        kwargs['employer_form'] = EmployerSignupForm
        return super().get_context_data(**kwargs)
    
class EmployerProfile(EmployerRequiredMixin, TemplateView):
    template_name = 'users/employer/emp_profile.html'

class EmployerProfileEdit(EmployerRequiredMixin, TemplateView):
    template_name = 'users/employer/emp_editprofile.html'

    def post(self, request):
        user_form = UpdateForm(request.POST, instance=request.user)
        worker_form = EmployerUpdateFormMore(request.POST, instance=request.user.employermore)
        if user_form.is_valid() and worker_form.is_valid():
            user_form.save()
            worker_form.save()
            return redirect(to='users:work_profile')
        else:
            print('not valid')

        return render(request, 'users/worker/work_editprofile.html')

class WorkerSignupView(SignupView, TemplateView):
    template_name = 'users/worker/work_signup.html'
    form_class = WorkerSignupForm

    def get_context_data(self, **kwargs):
        kwargs['worker_form'] = WorkerSignupForm
        return super().get_context_data(**kwargs)

class WorkerLoginView(LoginView, TemplateView):
    template_name = 'users/worker/work_login.html'

class WorkerProfile(WorkerRequiredMixin, TemplateView):
    template_name = 'users/worker/work_profile.html'

class WorkerProfileEdit(WorkerRequiredMixin, TemplateView):
    template_name = 'users/worker/work_editprofile.html'
    
    def post(self, request):
        user_form = UpdateForm(request.POST, instance=request.user)
        worker_form = WorkerUpdateFormMore(request.POST, instance=request.user.workermore)
        if user_form.is_valid() and worker_form.is_valid():
            user_form.save()
            worker_form.save()
            return redirect(to='users:work_profile')
        else:
            print('not valid')

        return render(request, 'users/worker/work_editprofile.html')
            

src/templates/users/employer/emp_editprofile.html
{% extends 'main.html' %}

{% block title %}Изменить профиль{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto p-6">
    <h1 class="mb-5 text-3xl">Редактировать профиль</h1>

    <form method="post" action="." class="space-y-3">
        {% csrf_token %}
        
        <div>
            <label>Имя</label>
            <input name="first_name" value="{{ request.user.first_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>Фамилия</label>
            <input name="last_name" value="{{ request.user.last_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>Логин</label>
            <input name="username" value="{{ request.user.username }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>E-mail</label>
            <input name="email" value="{{ request.user.email }}" type="email" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <button class="py-4 px-6 rounded-xl text-white bg-black">Отправить</button>
        </div>
    </form>
</div>
{% endblock %}

src/templates/users/employer/emp_login.html
{% extends 'main.html' %}

{% block content %}
  <h2>Login as Employer</h2>
  <form method="post" action="{% url 'account_login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

src/templates/users/employer/emp_profile.html
{% extends 'main.html' %}

{% block title %} Мой профиль {% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto p-6 px-6">
    <h1 class="mb-6 text-4xl">Профиль</h1>
    <div class="mx-auto">
        <div class="mb-6 text-2xl">
            <strong> Логин: </strong> {{ request.user.username }} <br>
            <strong> Тип: </strong> {{ request.user.type }}  <br>
            <strong> Email:  </strong> {{ request.user.email }} <br>
            <strong> Название компании: </strong> {{ request.user.name }} <br>
            <strong> Доп инфо: </strong> {{ request.user.employermore.testfield }} <br>
            <a href="#" class="absolute top-28 right-96 px-6 h-200 w-200 ">
                <img class="hover:shadow-lg rounded-xl" src="https://static.vecteezy.com/system/resources/thumbnails/023/986/562/small/telegram-logo-telegram-logo-transparent-telegram-icon-transparent-free-free-png.png" width="200" height="200">
            </a>
        </div>
    </div>
    <h2 class="my-6 text-2xl">Описание:</h2>
    <div class="w-full mb-6 p-5 flex flex-wrap bg-gray-100 rounded-xl">
        <div class="mb-6 w-full">
            <div class="product mb-6 flex pr-6">
                <div class="w-3/4 pl-6">
                    <div class="flex justify-between">
                        <a href="#" class="text-2xl">Lorem ipsum dolor sit amet 
                        consectetur adipisicing elit. Explicabo, beatae tempore 
                        doloremque adipisci consequuntur commodi optio illum! Q
                        uidem eius explicabo, earum corporis optio et eum unde veritatis, 
                        obcaecati cumque voluptates!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href={% url 'users:emp_editprofile' %}>
        <button class="button-reply-link font-mono px-3 py-3 rounded-xl text-black bg-teal-300 hover:bg-teal-400">
        Редактировать
        </button>
    </a>
</div>


{% endblock %}

src/templates/users/employer/emp_rofile.html
{% extends 'main.html' %}

{% block title %} Мой профиль {% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto p-6 px-6">
    <h1 class="mb-6 text-4xl">Профиль</h1>
    <div class="mx-auto">
        <div class="mb-6 text-2xl">
            <strong> Логин: </strong> {{ request.user.username }} <br>
            <strong> Тип: </strong> {{ request.user.type }}  <br>
            <strong> Email:  </strong> {{ request.user.email }} <br>
            <strong> Название компании: </strong> {{ request.user.name }} <br>
            <strong> Доп инфо: </strong> инфо <br>
            <a href="#" class="absolute top-28 right-96 px-6 h-200 w-200 ">
                <img class="hover:shadow-lg rounded-xl" src="https://static.vecteezy.com/system/resources/thumbnails/023/986/562/small/telegram-logo-telegram-logo-transparent-telegram-icon-transparent-free-free-png.png" width="200" height="200">
            </a>
        </div>
    </div>
    <h2 class="my-6 text-2xl">Описание:</h2>
    <div class="w-full mb-6 p-5 flex flex-wrap bg-gray-100 rounded-xl">
        <div class="mb-6 w-full">
            <div class="product mb-6 flex pr-6">
                <div class="w-3/4 pl-6">
                    <div class="flex justify-between">
                        <a href="#" class="text-2xl">Lorem ipsum dolor sit amet 
                        consectetur adipisicing elit. Explicabo, beatae tempore 
                        doloremque adipisci consequuntur commodi optio illum! Q
                        uidem eius explicabo, earum corporis optio et eum unde veritatis, 
                        obcaecati cumque voluptates!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href={% url 'users:emp_editprofile' %}>
        <button class="button-reply-link font-mono px-3 py-3 rounded-xl text-black bg-teal-300 hover:bg-teal-400">
        Редактировать
        </button>
    </a>
</div>


{% endblock %}

src/templates/users/employer/emp_signup.html
{% extends 'main.html' %}
{% block content %}
<form method="post" class="space-y-4" novalidate>
  {% csrf_token %}
    <div class="flex items-center justify-center h-screen">
      <div class="bg-teal-200 py-8 rounded-md px-10 max-w-lg shadow-md">
        <h1 class="text-center text-lg font-bold bg-white rounded-md text-black">Регистрация</h1>
        <div class="space-y-4 mt-6">
          {{ employer_form }}
        </div>
        <button class="button is-succes w-full mt-5 bg-white text-black py-2 rounded-md font-semibold tracking-tight">Зарегистрироваться</button>
      </div>
    </div>
</form>
{% endblock %}

src/templates/users/employer/emplogin.html
{% extends 'main.html' %}

{% block content %}
  <h2>Login as Employer</h2>
  <form method="post" action="{% url 'account_login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

src/templates/users/employer/empsignup.html
{% extends 'main.html' %}
{% block content %}
<form method="post" class="space-y-4" novalidate>
  {% csrf_token %}
    <div class="flex items-center justify-center h-screen">
      <div class="bg-teal-200 py-8 rounded-md px-10 max-w-lg shadow-md">
        <h1 class="text-center text-lg font-bold bg-white rounded-md text-black">Регистрация</h1>
        <div class="space-y-4 mt-6">
          {{ employer_form }}
        </div>
        <button class="button is-succes w-full mt-5 bg-white text-black py-2 rounded-md font-semibold tracking-tight">Зарегистрироваться</button>
      </div>
    </div>
</form>
{% endblock %}

src/templates/users/employer/replyes.html
{% extends 'main.html' %}

{% block content %}
<div class="h-screen flex">
    <div class="relative md:container md:mx-auto h-full bg-white py-6">
        <div class="border-b-2 border-gray-400 my-6">
            <div class="absolute left-1/2 -ml-0.5 w-0.5 h-screen bg-gray-400"></div>
        </div>
        <div class="relative mx-8">
            <ul class="vacancies absolute inset-y-0 left-0 divide-y divide-gray-200 dark:divide-gray-700">
                {% for item in employer_storage %}
                {% with vacancy=item.vacancies %}
                <li class="px-16 pb-3 sm:pb-4">
                    {% include 'storage/partials/vacancy_single.html' %}                                      
                </li>
                {% endwith %}
                {% endfor %}
            </ul>
        </div>
        <div class="relative">
            <div class="absolute left-1/2 mx-8">
                <div class="max-w-6xl mx-auto flex flex-wrap py-4 px-4 xl:px-0">
                    <div class="vacancy-detail-container w-full">
                        <p class="vacancy-link-1 flex text-3xl font-medium text-gray-900 hover:text-gray-600 truncate">
                        </p>
                        <p class="vacancy-link-2 flex text-4xl font-medium text-gray-900 hover:text-gray-600 truncate">
                        </p>
                        <p class="vacancy-link-3 flex text-xl font-medium text-gray-600 truncate">
                        </p>
                        <p class="vacancy-link-4 flex text-xl font-medium my-6 text-black truncate">
                        </p>
                        <h class="vacancy-link-5 flex text-lg font-medium my-6 text-black">
                        </h>
                        <p class="vacancy-link-6 flex text-xl font-medium my-6 text-black truncate">
                        </p>
                    </div>
                    <div class="inline-flex" id="success" style="display: none;">
                        <button class="button-remove-link font-mono px-3 py-3 rounded-xl text-black bg-red-200 hover:bg-red-300"> 
                            Удалить 
                        </button>
                        <button class="font-mono px-3 py-3 rounded-xl text-black bg-teal-300 hover:bg-teal-400"> 
                            Откликнуться 
                        </button>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}